name: Sky130hd_temp-sense-generator

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  sky130hd_temp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Make Sky130HD Temp
        env:
                IMAGE_NAME: saicharan0112/openfasoc:stable
        run: |
          cd $GITHUB_WORKSPACE
          touch file.log
          docker run --rm\
            -e GITHUB_ACTIONS=1\
            -v $PDK_ROOT:$PDK_ROOT\
            -e PDK_ROOT=$PDK_ROOT\
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              export PDK_ROOT=/pdk_data/ &&\
              cd ./openfasoc/generators/temp-sense-gen &&\
              make sky130hd_temp\
            ">> file.log
            if grep "\[ERROR\]" file.log; then exit 1; else exit 0; fi
